### ISSUE TITLE
Standard Assets missing

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#28]
Standard Asset Image Effects are used in the demo.  Either remove their use or include them in the package, please.  Or maybe include the demos as a separate download?

**Comment by Seneral** [comment]
Yep, good point:) It's just for image effects (the script and the references in the scenes) so I'll likely remove them. I use only standard TC2 assets in the example scenenes otherwise.
Maybe if I want extended example scenes I will make it a seperate package that clearly needs StandardAssets or smth imported, but definitely not the main package.
