### ISSUE TITLE
Resource and Cache Location warnings in the console

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#29]
Please include the folder warnings in the settings and inspector.

**Comment by geekrelief** [comment]
I created a new project and the Node Painter settings loaded up another project's settings.  The other project had a different location for the Resource and Cache Folder.  

No warnings in the Settings or Inspector were displayed.  So the user has to look at the console.   After the fixing the Resource Location, the brush stamps appear in the inspector, but the brush cursor preview does not display on the terrain or the canvas preview.

**Comment by Seneral** [comment]
Got that fixed, Notifications are now shown instead of debugs - also paths only are now stored in a text file in ProjectSettings:)
Also allowed external paths to be selected, but still selecting a path in Assets will keep them local so it won't break when moving the project - this is what I ultimately wanted, you can now choose to store f.E. the cache on a seperate HDD.
