### ISSUE TITLE
TC2 presets don't save/load Node Painter Canvas

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#35]
Make it so presets / prefabs for TC2 save / load  properly with Node Painter Canvas nodes.  Right now the Node Painter component exists, but references to canvas aren't serialized.

**Comment by Seneral** [comment]
Canvases are identified by ID - these are changed each time the component is copied etc, which makes sense. Don't want to have multiple painter work on the same canvas, this would create issues. So, each time a prefab is instantiated, you would need the canvas to be copied (from a copy previously stored in the prefab). This could create alot of unwanted data.
I do think most of the time you instantiate a prefab you would want to paint something different... I might be wrong though.
Should I sill try implement that? Would be really difficult because of missing proper callbacks for prefab creation...

**Comment by Seneral** [comment]
Actually, just checked in the latest release version and they are saved perfectly fine... canvas ID is kept and so the canvas is the same.
It is not bad but creates the problem of potentially multiple canvases of the same ID... So it's rather a bug I have to fix, I'm afraid:/
