### ISSUE TITLE
Session buttons should be removed

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#4]
Session buttons are a development feature used in case of crashes.  The equivalent for the end user is using Import / Export Raw. 

The session buttons should be removed.

**Comment by Seneral** [comment]
Small correction: The session buttons are not equivalent but instead of saving to a user-specified path, it exports the canvas to the Cache at Node Painter/Cache and registeres this in the Editor Preferences to load in on next startup - it is used to save sessions over editor downtime:)
But yes it should be removed.

**Comment by geekrelief** [comment]
Does that Cache clear then old session if it exists when New Canvas is clicked for a node?

**Comment by Seneral** [comment]
Nope, only when the scene is closed or the save session button is clicked - then it's deleted

**Comment by Seneral** [comment]
Done and set for Beta 1.1
