### ISSUE TITLE
Painting breaks when in color mode when using multiple colors in one channel.

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#5]
I'm not sure what the Color mode is supposed to do.  But when I select the red color and paint in RGB mode, then I select green to paint.  The green paint flattens the red paint and breaks painting.

Doing this in any other color modes breaks terrain generation, but the placed paint can be seen in the RGBA mode.

**Comment by Seneral** [comment]
This sounds like a bug. Thanks for pointing it out to me:)
The Toolbar with the channel selection is for visualization only - if you select red, it should paint red (grayscale when selecting only the R channel to display).
Color mode was initially intended to be used in the color output, but it turns out that is also only operable with masks. It's left there because why not - you can use it to paint stuff to export, although it will have no use to TC2. Should I remove it?

**Comment by geekrelief** [comment]
I haven't had much experience with the Color output for TC2 yet, so I can't comment on its usefulness.  It might be best to ask on the unity forums if anyone needs it. *shrug*

**Comment by Seneral** [comment]
What exactly does it break? Does work as expected for me.
With overlapping, you probably mean that the generated TC output is not exactly as you expected - this is because TC2 uses grayscale mask and simply get's the maximum values of the texture - so if you paint green ontop of your red, it won't immediately show in the TC2 output, but instead it will only show when it's more than red (maximising the channels).
To preview what TC2 is gettings, select 'Max' from the channel toolbar.
Is it this you are talking about or something different?

**Comment by geekrelief** [comment]
It could be user error on my part, but here's what I'm doing.

- Create a canvas set for color.
- In RGB mode, Select the Red color and paint on the preview.
- Select the Green color and paint on the preview.  The preview now appears black.  Going back to Red and painting does nothing.

**Comment by Seneral** [comment]
Hm, still...
Could it be related to #3? Which resolution are you using?
Are any errors thrown in the console?

**Comment by geekrelief** [comment]
I'm using 1024x1024.  There are no errors in the console.

Here I paint in red
![paint_red](https://cloud.githubusercontent.com/assets/27040/23570206/171645fa-0018-11e7-8565-5311707ae2cd.png)
Paint in green and the terrain generation breaks and no green
![paint_green](https://cloud.githubusercontent.com/assets/27040/23570208/1a6028c0-0018-11e7-8f56-bd255686f36e.png)

You can see the strokes in RGBA, A, and Max.  Nothing is shown on R or G.
![max](https://cloud.githubusercontent.com/assets/27040/23570212/1e0e6ec8-0018-11e7-9686-b3247db98f23.png)

**Comment by Seneral** [comment]
Is this fixed in the latest beta 1.2?

**Comment by geekrelief** [comment]
This is fixed in beta 1.2!
