### ISSUE TITLE
Documentation on Clamp Color Mode needed

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#6]
What does this do?  When set to Stroke, the Preview paints once and then disappears when clicked on again.  Then painting is broken.

This message appears in the Console with each painting attempt afterwards:

Merging passes!
UnityEngine.Debug:Log(Object)
TerrainComposer2.TerrainPainter.Painting:EndPainting() (at Assets/Node Painter/Scripts/Core/Painting.cs:1242)
TerrainComposer2.TerrainPainter.Painting:PaintUpdate(String, Int32, Boolean, Boolean, Vector2) (at Assets/Node Painter/Scripts/Core/Painting.cs:1188)
TerrainComposer2.TerrainPainter.NodePainterEditor:OnSceneGUI() (at Assets/Node Painter/Scripts/Editor/NodePainterEditor.cs:87)
UnityEditor.DockArea:OnGUI()

**Comment by Seneral** [comment]
This is a Debug message, thanks for pointing that out - Stroke is clamping the current paint amount to a maximum value above the start value. For that, it is using a seperate paint pass so it knows which amount it already painted - thus the merging passes log at the end. Despite using two instead of one pass for painting it's still good.
FYI, the other option, Max, clamps the canvas to 0-1, so it's kind of obsolete.

**Comment by geekrelief** [comment]
Can you provide an example of how to use this?

**Comment by Seneral** [comment]
If you're in Color mode, it will use the color as the maximum value, else it will provide a seperate field when Sroke color clamp mode is selected.
Painting then performs as normal but tops out at the initial canvas value + max value specified. This is used in some very specific cases only...

**Comment by Seneral** [comment]
Will remove it in the latest beta 1.2 as it gives no apparent plus but creates confusion (and is incompatible with certain blend modes).  Left is only the Clamp 0-1 option.
